### ISSUE TITLE
 undefined reference to `boost::unit_test::unit_test_main(bool (*)(), int, char**)'  Error

### ISSUE THREAD

**Issue by zengletian1491** [alicevision/CCTag#118]
when "cmake .." and "make" are typed in, errors occurr as follows:

**[ 97%] Linking CXX executable cctag_fitEllipse
CMakeFiles/cctag_fitEllipse.dir/fitEllipse.cpp.o: In function `main':
fitEllipse.cpp:(.text.startup+0x9cd): undefined reference to `boost::unit_test::unit_test_main(bool (*)(), int, char**)'
collect2: error: ld returned 1 exit status
src/cctag/test/CMakeFiles/cctag_fitEllipse.dir/build.make:107: recipe for target 'src/cctag/test/cctag_fitEllipse' failed
make[2]: *** [src/cctag/test/cctag_fitEllipse] Error 1
CMakeFiles/Makefile2:277: recipe for target 'src/cctag/test/CMakeFiles/cctag_fitEllipse.dir/all' failed
make[1]: *** [src/cctag/test/CMakeFiles/cctag_fitEllipse.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2**

I use Boost1_70_0 and I do not know why. Would you please give me some suggestions?Thanks!

**Comment by simogasp** [comment]
that's strange. Can you post the output of the first `cmake ..` (when done from scratch, i.e. removing the CMakeCache.txt file or doing it from another directory)?

BTW if the problem is limited to only this target you can avoid building the unit tests (which is unlikely something you need) running `cmake .. -DBUILD_TESTS:BOOL=OFF`.
But it's interesting to know what's wrong with that message.

**Comment by zengletian1491** [comment]
> that's strange. Can you post the output of the first `cmake ..` (when done from scratch, i.e. removing the CMakeCache.txt file or doing it from another directory)?
> 
> BTW if the problem is limited to only this target you can avoid building the unit tests (which is unlikely something you need) running `cmake .. -DBUILD_TESTS:BOOL=OFF`.
> But it's interesting to know what's wrong with that message.

Thanks very much! It is OK!
