### ISSUE TITLE
CCtags printing details

### ISSUE THREAD

**Issue by spono** [alicevision/CCTag#127]
Hi,
I'm pretty new to Meshroom and photogrammetry.
I read the paper explaining hot the system works but I didn't find any specific info related to the tags themselves, either in the Github issues raised in the Meshroom section or in the manual.

1. Do they need a specific size in order to allow for proper scaling?
2. Do they need a specific colour or not?

Thanks in advance!

**Comment by lcalvet** [comment]
Hi @spono,
Thanks for your interest. 
1. You can rescale your scene from any measurements in your scene. The scale factor can be either computed from a know distance between two or more cctag centers or from the radius of the printed cctags.
2. Black is optimal to maximize the contrast but if your are using cctag under normal, namely non challenging, shooting conditions then it is fine to use any other color. Just keep in mind that the darker the better.
Cheers.

**Comment by spono** [comment]
HI @lcalvet ,

> 1. You can rescale your scene from any measurements in your scene. The scale factor can be either computed from a know distance between two or more cctag centers or from the radius of the printed cctags.

Ok, great. I was just checking because other SW provide tags with specific sizes and I don't know if the size itself can affect the recognition of tags from the algorithm.
As a general suggestion, I would add the centre (a simple dot) to the provied cctags. This could help also the precise positioning of a GPS, when placed in open spaces.


> 2. Black is optimal to maximize the contrast but if your are using cctag under normal, namely non challenging, shooting conditions then it is fine to use any other color. Just keep in mind that the darker the better.

good to know: using different colors could become handy for other automated recognition...but yeah: outside buildings with lots of sun might be the case to keep goin' with plain black.

Thank you very much!

**Comment by elektrokokke** [comment]
Hi Spono,

having a little dot in the centre should pose no problems. I put a little cross, which does not interfere neither with detection nor decoding.

For outside scenes with direct sunlight it might make sense to use a light grey instead of white for the background, as overexposure leads to errors in decoding. This is because the black ellipses can get "thinned" by overexposure of the background. And, as most of the objects in an outdoor scene will be darker than white, automatic exposure tends to lead to overexposure of the CCTag background.
An alternative would be to deliberately underexpose the pictures.

**Comment by spono** [comment]
wow, that's a great hint...thank you so much!

**Comment by simogasp** [comment]
Also note that now you can generate the cctag to print
https://github.com/alicevision/CCTag/tree/develop/markersToPrint/generators
Check the doc for the usage:
https://cctag.readthedocs.io/en/doc-first/markers/markers.html

Hope it helps
