### ISSUE TITLE
CCTag (subpixel) accuracy

### ISSUE THREAD

**Issue by anauta00** [alicevision/CCTag#204]
Hi,

I have a question about the accuracy of the center position detection in CCTag.

For a specific use, I have coded my own (complicated but functional) center position detection algorithms for concentric circles.
It uses OpenCV's feature detection mostly...
The accuracy I reach on synthetic images (known center positions) is very good,  like <0.05 pixels.

Using CCTag, which I would prefer, the accuracy is less (and the results vary for each run).

Can I improve the accuracy of the CCTag library somehow? Are there some settings I need to change?

Thanks and greetings,
Auke Nauta

**Comment by OndrejIvancik** [comment]
Hi Anauta00,
the subpixel [accuracy and precision](https://wp.stolaf.edu/it/gis-precision-accuracy/) of detection is a bit disapointing in version 1.0.3 especially on generated ideal images. You can easilly find out that the returned positions have negative offset in x and y direction:

![cctag_not_accurate_not_precise](https://github.com/alicevision/CCTag/assets/75783056/24001ea3-c9d8-4491-9e96-43dea5478a87)
These are the deviations between cctag detected and expected positions for all reliable 4-crown markers. Mean offset vector is [-0.3983, -0.340] pixels.
The marker images contains one marker with radius 100 pixels, like this:
<img width="170" alt="cctag_marker_id0" src="https://github.com/alicevision/CCTag/assets/75783056/3aab46b1-81f5-49a3-bb88-d5939f1af389">

When you change the parameter _numSamplesOuterEdgePointsRefinement to 100 (cctag::Parameters), the precision will be much better, but now with the offest vector [-0.5151, -0.513]:
![cctag_not_accurate_precise](https://github.com/alicevision/CCTag/assets/75783056/d1e25750-1874-448d-b460-446256f96e09)

This nicely proofs that all the positions are returned with half-pixel error, what I reported some time ago [https://github.com/alicevision/CCTag/issues/122](url). Hopefully it will be fixed in next release. For now you only have to add 0.5 to x and y coordinate to get accurate and precise results with mean offset vector of [-0.0152, -0.011] pixels:
![cctag_accurate_precise](https://github.com/alicevision/CCTag/assets/75783056/13be3f93-91f2-489b-8019-31569ae9b207)

I hope it helps you.
