### ISSUE TITLE
Estimate distance in camera frame

### ISSUE THREAD

**Issue by mojovski** [alicevision/CCTag#63]
Hi,
is it possible to get the distance to the marker after it has been detected?

Thank you very much!

**Comment by lcalvet** [comment]
Hi mojovski,
It can theoretically be achieved either when camera intrinsics are (i) known or (ii) unknown. 
(i) You must first decompose the homography matrix (see CCTag.hpp) using K in order to get the rotational and translational part of the supporting plane pose. With such a pattern, there is an ambiguity in terms of pose "around" the normal axis through the center of the marker orthogonal to the supporting plane. Since you are interested in the distance from the optical center to the marker, it doesn't matter, just consider the norm of the translation vector which gives you the actual distance.
Such matrix decomposition is described in Algorithms for Plane-Based Pose Estimation (CVPR00)
(ii) You need first to compute the calibration matrix K. The circular points-pair embedded by such a pattern allows you to compute the focal length, provided known principal point and pixel of known shape. Typically, you "put" the principal point at the center of the image and assume square pixels, the K matrix end up being parametrised by the sole focal length. 
The focal length can be computed e.g. by using the equation 4 from On Plane-Based Camera Calibration: A General Algorithm, Singularities, Applications, CVPR99 (equation 4). Then go to (i).

**Comment by mojovski** [comment]
Hi,
thank you!
So from your answer I conclude, that its not implemented yet, right? :)

As for the pose and distance estimation, I can tell that this implementation of iterative (robust) PnP http://xuchi.weebly.com/rpnp.html outperforms the methods in OpenCV (the error was <20% of the OpenCV errors in some experiments).

**Comment by lcalvet** [comment]
Hi mojovski,
Yes, you are right.

**Comment by Akumar201** [comment]
Hello, I would like to know as this issue was posted on 2017 , does we have a implementation now in 2022 where we can estimate camera pose detection or used it to find the distance between camera and marker. Thank you

**Comment by simogasp** [comment]
no there is no implementation at the moment in the library

**Comment by Akumar201** [comment]
I would like to know is there any possible way I can use your library to get camera coordinates with respect to CCTag
