### ISSUE TITLE
can i use it with my cpu?

### ISSUE THREAD

**Issue by Dylanin1999** [alicevision/CCTag#75]
can i use it with my cpu? if it is possible ,can you teach my how to do .thank you

**Comment by simogasp** [comment]
Hi @Dylanin1999 
yes the library can run in cpu-only mode, so you don't need to have a GPU on your machine.

In order to build the library in cpu-mode, you can follow the steps in [BUILD](https://github.com/alicevision/CCTag/blob/develop/BUILD.md) file (note that for now it successfully builds only on Linux and MacOSX).

Once you get all the required dependencies, in the [building step](https://github.com/alicevision/CCTag/blob/develop/BUILD.md#run-the-building-process) you just need to add `-DWITH_CUDA:BOOL=OFF` in the `cmake .. ` line, _ie_ something like
```bash
cmake .. -DOpenCV_DIR=${OPENCV_INSTALL}/share/share/OpenCV/ -DWITH_CUDA:BOOL=OFF
```
Hope it helps.

S.

**Comment by 99991** [comment]
I get the following warning when using `-DWITH_CUDA:BOOL=OFF`:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    WITH_CUDA
```

Using `-DCCTAG_WITH_CUDA:BOOL=OFF` instead works for me.

**Comment by simogasp** [comment]
yes it has been changed lately to be more consistent with the other options naming.
But, you are right, we need to improve the documentation...
